// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_WEATHERAPI_OPENMETEO_SDK_H_
#define FLATBUFFERS_GENERATED_WEATHERAPI_OPENMETEO_SDK_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace openmeteo_sdk {

struct VariableWithValues;
struct VariableWithValuesBuilder;

struct VariablesWithTime;
struct VariablesWithTimeBuilder;

struct VariablesWithMonth;
struct VariablesWithMonthBuilder;

struct WeatherApiResponse;
struct WeatherApiResponseBuilder;

enum class Unit : uint8_t {
  undefined = 0,
  celsius = 1,
  centimetre = 2,
  cubic_metre_per_cubic_metre = 3,
  cubic_metre_per_second = 4,
  degree_direction = 5,
  dimensionless_integer = 6,
  dimensionless = 7,
  european_air_quality_index = 8,
  fahrenheit = 9,
  feet = 10,
  fraction = 11,
  gdd_celsius = 12,
  geopotential_metre = 13,
  grains_per_cubic_metre = 14,
  gram_per_kilogram = 15,
  hectopascal = 16,
  hours = 17,
  inch = 18,
  iso8601 = 19,
  joule_per_kilogram = 20,
  kelvin = 21,
  kilopascal = 22,
  kilogram_per_square_metre = 23,
  kilometres_per_hour = 24,
  knots = 25,
  megajoule_per_square_metre = 26,
  metre_per_second_not_unit_converted = 27,
  metre_per_second = 28,
  metre = 29,
  micrograms_per_cubic_metre = 30,
  miles_per_hour = 31,
  millimetre = 32,
  pascal = 33,
  per_second = 34,
  percentage = 35,
  seconds = 36,
  unix_time = 37,
  us_air_quality_index = 38,
  watt_per_square_metre = 39,
  wmo_code = 40,
  parts_per_million = 41,
  kilogram_per_cubic_metre = 42
};

inline const Unit (&EnumValuesUnit())[43] {
  static const Unit values[] = {
    Unit::undefined,
    Unit::celsius,
    Unit::centimetre,
    Unit::cubic_metre_per_cubic_metre,
    Unit::cubic_metre_per_second,
    Unit::degree_direction,
    Unit::dimensionless_integer,
    Unit::dimensionless,
    Unit::european_air_quality_index,
    Unit::fahrenheit,
    Unit::feet,
    Unit::fraction,
    Unit::gdd_celsius,
    Unit::geopotential_metre,
    Unit::grains_per_cubic_metre,
    Unit::gram_per_kilogram,
    Unit::hectopascal,
    Unit::hours,
    Unit::inch,
    Unit::iso8601,
    Unit::joule_per_kilogram,
    Unit::kelvin,
    Unit::kilopascal,
    Unit::kilogram_per_square_metre,
    Unit::kilometres_per_hour,
    Unit::knots,
    Unit::megajoule_per_square_metre,
    Unit::metre_per_second_not_unit_converted,
    Unit::metre_per_second,
    Unit::metre,
    Unit::micrograms_per_cubic_metre,
    Unit::miles_per_hour,
    Unit::millimetre,
    Unit::pascal,
    Unit::per_second,
    Unit::percentage,
    Unit::seconds,
    Unit::unix_time,
    Unit::us_air_quality_index,
    Unit::watt_per_square_metre,
    Unit::wmo_code,
    Unit::parts_per_million,
    Unit::kilogram_per_cubic_metre
  };
  return values;
}

inline const char * const *EnumNamesUnit() {
  static const char * const names[44] = {
    "undefined",
    "celsius",
    "centimetre",
    "cubic_metre_per_cubic_metre",
    "cubic_metre_per_second",
    "degree_direction",
    "dimensionless_integer",
    "dimensionless",
    "european_air_quality_index",
    "fahrenheit",
    "feet",
    "fraction",
    "gdd_celsius",
    "geopotential_metre",
    "grains_per_cubic_metre",
    "gram_per_kilogram",
    "hectopascal",
    "hours",
    "inch",
    "iso8601",
    "joule_per_kilogram",
    "kelvin",
    "kilopascal",
    "kilogram_per_square_metre",
    "kilometres_per_hour",
    "knots",
    "megajoule_per_square_metre",
    "metre_per_second_not_unit_converted",
    "metre_per_second",
    "metre",
    "micrograms_per_cubic_metre",
    "miles_per_hour",
    "millimetre",
    "pascal",
    "per_second",
    "percentage",
    "seconds",
    "unix_time",
    "us_air_quality_index",
    "watt_per_square_metre",
    "wmo_code",
    "parts_per_million",
    "kilogram_per_cubic_metre",
    nullptr
  };
  return names;
}

inline const char *EnumNameUnit(Unit e) {
  if (::flatbuffers::IsOutRange(e, Unit::undefined, Unit::kilogram_per_cubic_metre)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesUnit()[index];
}

enum class Model : uint8_t {
  undefined = 0,
  best_match = 1,
  gfs_seamless = 2,
  gfs_global = 3,
  gfs_hrrr = 4,
  meteofrance_seamless = 5,
  meteofrance_arpege_seamless = 6,
  meteofrance_arpege_world = 7,
  meteofrance_arpege_europe = 8,
  meteofrance_arome_seamless = 9,
  meteofrance_arome_france = 10,
  meteofrance_arome_france_hd = 11,
  jma_seamless = 12,
  jma_msm = 13,
  jms_gsm = 14,
  jma_gsm = 15,
  gem_seamless = 16,
  gem_global = 17,
  gem_regional = 18,
  gem_hrdps_continental = 19,
  icon_seamless = 20,
  icon_global = 21,
  icon_eu = 22,
  icon_d2 = 23,
  ecmwf_ifs04 = 24,
  metno_nordic = 25,
  era5_seamless = 26,
  era5 = 27,
  cerra = 28,
  era5_land = 29,
  ecmwf_ifs = 30,
  gwam = 31,
  ewam = 32,
  glofas_seamless_v3 = 33,
  glofas_forecast_v3 = 34,
  glofas_consolidated_v3 = 35,
  glofas_seamless_v4 = 36,
  glofas_forecast_v4 = 37,
  glofas_consolidated_v4 = 38,
  gfs025 = 39,
  gfs05 = 40,
  CMCC_CM2_VHR4 = 41,
  FGOALS_f3_H_highresSST = 42,
  FGOALS_f3_H = 43,
  HiRAM_SIT_HR = 44,
  MRI_AGCM3_2_S = 45,
  EC_Earth3P_HR = 46,
  MPI_ESM1_2_XR = 47,
  NICAM16_8S = 48,
  cams_europe = 49,
  cams_global = 50,
  cfsv2 = 51,
  era5_ocean = 52,
  cma_grapes_global = 53,
  bom_access_global = 54,
  bom_access_global_ensemble = 55,
  arpae_cosmo_seamless = 56,
  arpae_cosmo_2i = 57,
  arpae_cosmo_2i_ruc = 58,
  arpae_cosmo_5m = 59,
  ecmwf_ifs025 = 60,
  ecmwf_aifs025 = 61,
  gfs013 = 62,
  gfs_graphcast025 = 63,
  ecmwf_wam025 = 64,
  meteofrance_wave = 65,
  meteofrance_currents = 66,
  ecmwf_wam025_ensemble = 67,
  ncep_gfswave025 = 68,
  ncep_gefswave025 = 69,
  knmi_seamless = 70,
  knmi_harmonie_arome_europe = 71,
  knmi_harmonie_arome_netherlands = 72,
  dmi_seamless = 73,
  dmi_harmonie_arome_europe = 74,
  metno_seamless = 75,
  era5_ensemble = 76,
  ecmwf_ifs_analysis = 77,
  ecmwf_ifs_long_window = 78,
  ecmwf_ifs_analysis_long_window = 79,
  ukmo_global_deterministic_10km = 80,
  ukmo_uk_deterministic_2km = 81,
  ukmo_seamless = 82,
  ncep_gfswave016 = 83,
  ncep_nbm_conus = 84,
  ukmo_global_ensemble_20km = 85,
  ecmwf_aifs025_single = 86,
  jma_jaxa_himawari = 87,
  eumetsat_sarah3 = 88,
  eumetsat_lsa_saf_msg = 89,
  eumetsat_lsa_saf_iodc = 90,
  satellite_radiation_seamless = 91,
  kma_gdps = 92,
  kma_ldps = 93,
  kma_seamless = 94,
  italia_meteo_arpae_icon_2i = 95,
  ukmo_uk_ensemble_2km = 96,
  meteofrance_arome_france_hd_15min = 97,
  meteofrance_arome_france_15min = 98,
  meteoswiss_icon_ch1 = 99,
  meteoswiss_icon_ch2 = 100,
  meteoswiss_icon_ch1_ensemble = 101,
  meteoswiss_icon_ch2_ensemble = 102,
  meteoswiss_icon_seamless = 103,
  ncep_nam_conus = 104,
  icon_d2_ruc = 105,
  ecmwf_seas5 = 106,
  ecmwf_ec46 = 107,
  ecmwf_seasonal_seamless = 108,
  ecmwf_ifs_seamless = 109,
  jma_jaxa_mtg_fci = 110,
  gem_hrdps_west = 111,
  ecmwf_wam = 112,
  ncep_aigfs025 = 113,
  ncep_aigefs025 = 114,
  ncep_hgefs025_ensemble_mean = 115,
  ecmwf_seasonal_ensemble_mean_seamless = 116,
  ecmwf_seas5_ensemble_mean = 117,
  ecmwf_ec46_ensemble_mean = 118,
  ncep_aigefs025_ensemble_mean = 119,
  dwd_icon_eps_ensemble_mean_seamless = 120,
  dwd_icon_eps_ensemble_mean = 121,
  dwd_icon_eu_eps_ensemble_mean = 122,
  dwd_icon_d2_eps_ensemble_mean = 123,
  ncep_gefs_ensemble_mean_seamless = 124,
  ncep_gefs025_ensemble_mean = 125,
  ncep_gefs05_ensemble_mean = 126,
  ecmwf_ifs025_ensemble_mean = 127,
  ecmwf_aifs025_ensemble_mean = 128,
  meteoswiss_icon_ch1_ensemble_mean = 129,
  meteoswiss_icon_ch2_ensemble_mean = 130,
  cmc_gem_geps_ensemble_mean = 131,
  ukmo_global_ensemble_mean_20km = 132,
  ukmo_uk_ensemble_mean_2km = 133,
  dwd_sis_europe_africa_v4 = 134,
  bom_access_global_ensemble_mean = 135,
  ecmwf_wam025_ensemble_mean = 136,
  ncep_gefswave025_ensemble_mean = 137,
  geosphere_arome_austria = 138,
  geosphere_seamless = 139,
  chmi_aladin_cz_1km = 140,
  ecmwf_ifs_europe_ensemble = 141,
  ecmwf_ifs_europe_ensemble_mean = 142,
  ecmwf_aifs_europe_ensemble = 143,
  ecmwf_aifs_europe_ensemble_mean = 144,
  google_weathernext2_ensemble = 145,
  google_weathernext2_ensemble_mean = 146
};

inline const Model (&EnumValuesModel())[147] {
  static const Model values[] = {
    Model::undefined,
    Model::best_match,
    Model::gfs_seamless,
    Model::gfs_global,
    Model::gfs_hrrr,
    Model::meteofrance_seamless,
    Model::meteofrance_arpege_seamless,
    Model::meteofrance_arpege_world,
    Model::meteofrance_arpege_europe,
    Model::meteofrance_arome_seamless,
    Model::meteofrance_arome_france,
    Model::meteofrance_arome_france_hd,
    Model::jma_seamless,
    Model::jma_msm,
    Model::jms_gsm,
    Model::jma_gsm,
    Model::gem_seamless,
    Model::gem_global,
    Model::gem_regional,
    Model::gem_hrdps_continental,
    Model::icon_seamless,
    Model::icon_global,
    Model::icon_eu,
    Model::icon_d2,
    Model::ecmwf_ifs04,
    Model::metno_nordic,
    Model::era5_seamless,
    Model::era5,
    Model::cerra,
    Model::era5_land,
    Model::ecmwf_ifs,
    Model::gwam,
    Model::ewam,
    Model::glofas_seamless_v3,
    Model::glofas_forecast_v3,
    Model::glofas_consolidated_v3,
    Model::glofas_seamless_v4,
    Model::glofas_forecast_v4,
    Model::glofas_consolidated_v4,
    Model::gfs025,
    Model::gfs05,
    Model::CMCC_CM2_VHR4,
    Model::FGOALS_f3_H_highresSST,
    Model::FGOALS_f3_H,
    Model::HiRAM_SIT_HR,
    Model::MRI_AGCM3_2_S,
    Model::EC_Earth3P_HR,
    Model::MPI_ESM1_2_XR,
    Model::NICAM16_8S,
    Model::cams_europe,
    Model::cams_global,
    Model::cfsv2,
    Model::era5_ocean,
    Model::cma_grapes_global,
    Model::bom_access_global,
    Model::bom_access_global_ensemble,
    Model::arpae_cosmo_seamless,
    Model::arpae_cosmo_2i,
    Model::arpae_cosmo_2i_ruc,
    Model::arpae_cosmo_5m,
    Model::ecmwf_ifs025,
    Model::ecmwf_aifs025,
    Model::gfs013,
    Model::gfs_graphcast025,
    Model::ecmwf_wam025,
    Model::meteofrance_wave,
    Model::meteofrance_currents,
    Model::ecmwf_wam025_ensemble,
    Model::ncep_gfswave025,
    Model::ncep_gefswave025,
    Model::knmi_seamless,
    Model::knmi_harmonie_arome_europe,
    Model::knmi_harmonie_arome_netherlands,
    Model::dmi_seamless,
    Model::dmi_harmonie_arome_europe,
    Model::metno_seamless,
    Model::era5_ensemble,
    Model::ecmwf_ifs_analysis,
    Model::ecmwf_ifs_long_window,
    Model::ecmwf_ifs_analysis_long_window,
    Model::ukmo_global_deterministic_10km,
    Model::ukmo_uk_deterministic_2km,
    Model::ukmo_seamless,
    Model::ncep_gfswave016,
    Model::ncep_nbm_conus,
    Model::ukmo_global_ensemble_20km,
    Model::ecmwf_aifs025_single,
    Model::jma_jaxa_himawari,
    Model::eumetsat_sarah3,
    Model::eumetsat_lsa_saf_msg,
    Model::eumetsat_lsa_saf_iodc,
    Model::satellite_radiation_seamless,
    Model::kma_gdps,
    Model::kma_ldps,
    Model::kma_seamless,
    Model::italia_meteo_arpae_icon_2i,
    Model::ukmo_uk_ensemble_2km,
    Model::meteofrance_arome_france_hd_15min,
    Model::meteofrance_arome_france_15min,
    Model::meteoswiss_icon_ch1,
    Model::meteoswiss_icon_ch2,
    Model::meteoswiss_icon_ch1_ensemble,
    Model::meteoswiss_icon_ch2_ensemble,
    Model::meteoswiss_icon_seamless,
    Model::ncep_nam_conus,
    Model::icon_d2_ruc,
    Model::ecmwf_seas5,
    Model::ecmwf_ec46,
    Model::ecmwf_seasonal_seamless,
    Model::ecmwf_ifs_seamless,
    Model::jma_jaxa_mtg_fci,
    Model::gem_hrdps_west,
    Model::ecmwf_wam,
    Model::ncep_aigfs025,
    Model::ncep_aigefs025,
    Model::ncep_hgefs025_ensemble_mean,
    Model::ecmwf_seasonal_ensemble_mean_seamless,
    Model::ecmwf_seas5_ensemble_mean,
    Model::ecmwf_ec46_ensemble_mean,
    Model::ncep_aigefs025_ensemble_mean,
    Model::dwd_icon_eps_ensemble_mean_seamless,
    Model::dwd_icon_eps_ensemble_mean,
    Model::dwd_icon_eu_eps_ensemble_mean,
    Model::dwd_icon_d2_eps_ensemble_mean,
    Model::ncep_gefs_ensemble_mean_seamless,
    Model::ncep_gefs025_ensemble_mean,
    Model::ncep_gefs05_ensemble_mean,
    Model::ecmwf_ifs025_ensemble_mean,
    Model::ecmwf_aifs025_ensemble_mean,
    Model::meteoswiss_icon_ch1_ensemble_mean,
    Model::meteoswiss_icon_ch2_ensemble_mean,
    Model::cmc_gem_geps_ensemble_mean,
    Model::ukmo_global_ensemble_mean_20km,
    Model::ukmo_uk_ensemble_mean_2km,
    Model::dwd_sis_europe_africa_v4,
    Model::bom_access_global_ensemble_mean,
    Model::ecmwf_wam025_ensemble_mean,
    Model::ncep_gefswave025_ensemble_mean,
    Model::geosphere_arome_austria,
    Model::geosphere_seamless,
    Model::chmi_aladin_cz_1km,
    Model::ecmwf_ifs_europe_ensemble,
    Model::ecmwf_ifs_europe_ensemble_mean,
    Model::ecmwf_aifs_europe_ensemble,
    Model::ecmwf_aifs_europe_ensemble_mean,
    Model::google_weathernext2_ensemble,
    Model::google_weathernext2_ensemble_mean
  };
  return values;
}

inline const char * const *EnumNamesModel() {
  static const char * const names[148] = {
    "undefined",
    "best_match",
    "gfs_seamless",
    "gfs_global",
    "gfs_hrrr",
    "meteofrance_seamless",
    "meteofrance_arpege_seamless",
    "meteofrance_arpege_world",
    "meteofrance_arpege_europe",
    "meteofrance_arome_seamless",
    "meteofrance_arome_france",
    "meteofrance_arome_france_hd",
    "jma_seamless",
    "jma_msm",
    "jms_gsm",
    "jma_gsm",
    "gem_seamless",
    "gem_global",
    "gem_regional",
    "gem_hrdps_continental",
    "icon_seamless",
    "icon_global",
    "icon_eu",
    "icon_d2",
    "ecmwf_ifs04",
    "metno_nordic",
    "era5_seamless",
    "era5",
    "cerra",
    "era5_land",
    "ecmwf_ifs",
    "gwam",
    "ewam",
    "glofas_seamless_v3",
    "glofas_forecast_v3",
    "glofas_consolidated_v3",
    "glofas_seamless_v4",
    "glofas_forecast_v4",
    "glofas_consolidated_v4",
    "gfs025",
    "gfs05",
    "CMCC_CM2_VHR4",
    "FGOALS_f3_H_highresSST",
    "FGOALS_f3_H",
    "HiRAM_SIT_HR",
    "MRI_AGCM3_2_S",
    "EC_Earth3P_HR",
    "MPI_ESM1_2_XR",
    "NICAM16_8S",
    "cams_europe",
    "cams_global",
    "cfsv2",
    "era5_ocean",
    "cma_grapes_global",
    "bom_access_global",
    "bom_access_global_ensemble",
    "arpae_cosmo_seamless",
    "arpae_cosmo_2i",
    "arpae_cosmo_2i_ruc",
    "arpae_cosmo_5m",
    "ecmwf_ifs025",
    "ecmwf_aifs025",
    "gfs013",
    "gfs_graphcast025",
    "ecmwf_wam025",
    "meteofrance_wave",
    "meteofrance_currents",
    "ecmwf_wam025_ensemble",
    "ncep_gfswave025",
    "ncep_gefswave025",
    "knmi_seamless",
    "knmi_harmonie_arome_europe",
    "knmi_harmonie_arome_netherlands",
    "dmi_seamless",
    "dmi_harmonie_arome_europe",
    "metno_seamless",
    "era5_ensemble",
    "ecmwf_ifs_analysis",
    "ecmwf_ifs_long_window",
    "ecmwf_ifs_analysis_long_window",
    "ukmo_global_deterministic_10km",
    "ukmo_uk_deterministic_2km",
    "ukmo_seamless",
    "ncep_gfswave016",
    "ncep_nbm_conus",
    "ukmo_global_ensemble_20km",
    "ecmwf_aifs025_single",
    "jma_jaxa_himawari",
    "eumetsat_sarah3",
    "eumetsat_lsa_saf_msg",
    "eumetsat_lsa_saf_iodc",
    "satellite_radiation_seamless",
    "kma_gdps",
    "kma_ldps",
    "kma_seamless",
    "italia_meteo_arpae_icon_2i",
    "ukmo_uk_ensemble_2km",
    "meteofrance_arome_france_hd_15min",
    "meteofrance_arome_france_15min",
    "meteoswiss_icon_ch1",
    "meteoswiss_icon_ch2",
    "meteoswiss_icon_ch1_ensemble",
    "meteoswiss_icon_ch2_ensemble",
    "meteoswiss_icon_seamless",
    "ncep_nam_conus",
    "icon_d2_ruc",
    "ecmwf_seas5",
    "ecmwf_ec46",
    "ecmwf_seasonal_seamless",
    "ecmwf_ifs_seamless",
    "jma_jaxa_mtg_fci",
    "gem_hrdps_west",
    "ecmwf_wam",
    "ncep_aigfs025",
    "ncep_aigefs025",
    "ncep_hgefs025_ensemble_mean",
    "ecmwf_seasonal_ensemble_mean_seamless",
    "ecmwf_seas5_ensemble_mean",
    "ecmwf_ec46_ensemble_mean",
    "ncep_aigefs025_ensemble_mean",
    "dwd_icon_eps_ensemble_mean_seamless",
    "dwd_icon_eps_ensemble_mean",
    "dwd_icon_eu_eps_ensemble_mean",
    "dwd_icon_d2_eps_ensemble_mean",
    "ncep_gefs_ensemble_mean_seamless",
    "ncep_gefs025_ensemble_mean",
    "ncep_gefs05_ensemble_mean",
    "ecmwf_ifs025_ensemble_mean",
    "ecmwf_aifs025_ensemble_mean",
    "meteoswiss_icon_ch1_ensemble_mean",
    "meteoswiss_icon_ch2_ensemble_mean",
    "cmc_gem_geps_ensemble_mean",
    "ukmo_global_ensemble_mean_20km",
    "ukmo_uk_ensemble_mean_2km",
    "dwd_sis_europe_africa_v4",
    "bom_access_global_ensemble_mean",
    "ecmwf_wam025_ensemble_mean",
    "ncep_gefswave025_ensemble_mean",
    "geosphere_arome_austria",
    "geosphere_seamless",
    "chmi_aladin_cz_1km",
    "ecmwf_ifs_europe_ensemble",
    "ecmwf_ifs_europe_ensemble_mean",
    "ecmwf_aifs_europe_ensemble",
    "ecmwf_aifs_europe_ensemble_mean",
    "google_weathernext2_ensemble",
    "google_weathernext2_ensemble_mean",
    nullptr
  };
  return names;
}

inline const char *EnumNameModel(Model e) {
  if (::flatbuffers::IsOutRange(e, Model::undefined, Model::google_weathernext2_ensemble_mean)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesModel()[index];
}

enum class Variable : uint8_t {
  undefined = 0,
  apparent_temperature = 1,
  cape = 2,
  cloud_cover = 3,
  cloud_cover_high = 4,
  cloud_cover_low = 5,
  cloud_cover_mid = 6,
  daylight_duration = 7,
  dew_point = 8,
  diffuse_radiation = 9,
  diffuse_radiation_instant = 10,
  direct_normal_irradiance = 11,
  direct_normal_irradiance_instant = 12,
  direct_radiation = 13,
  direct_radiation_instant = 14,
  et0_fao_evapotranspiration = 15,
  evapotranspiration = 16,
  freezing_level_height = 17,
  growing_degree_days = 18,
  is_day = 19,
  latent_heat_flux = 20,
  leaf_wetness_probability = 21,
  lifted_index = 22,
  lightning_potential = 23,
  precipitation = 24,
  precipitation_hours = 25,
  precipitation_probability = 26,
  pressure_msl = 27,
  rain = 28,
  relative_humidity = 29,
  runoff = 30,
  sensible_heat_flux = 31,
  shortwave_radiation = 32,
  shortwave_radiation_instant = 33,
  showers = 34,
  snow_depth = 35,
  snow_height = 36,
  snowfall = 37,
  snowfall_height = 38,
  snowfall_water_equivalent = 39,
  sunrise = 40,
  sunset = 41,
  soil_moisture = 42,
  soil_moisture_index = 43,
  soil_temperature = 44,
  surface_pressure = 45,
  surface_temperature = 46,
  temperature = 47,
  terrestrial_radiation = 48,
  terrestrial_radiation_instant = 49,
  total_column_integrated_water_vapour = 50,
  updraft = 51,
  uv_index = 52,
  uv_index_clear_sky = 53,
  vapour_pressure_deficit = 54,
  visibility = 55,
  weather_code = 56,
  wind_direction = 57,
  wind_gusts = 58,
  wind_speed = 59,
  vertical_velocity = 60,
  geopotential_height = 61,
  wet_bulb_temperature = 62,
  river_discharge = 63,
  wave_height = 64,
  wave_period = 65,
  wave_direction = 66,
  wind_wave_height = 67,
  wind_wave_period = 68,
  wind_wave_peak_period = 69,
  wind_wave_direction = 70,
  swell_wave_height = 71,
  swell_wave_period = 72,
  swell_wave_peak_period = 73,
  swell_wave_direction = 74,
  pm10 = 75,
  pm2p5 = 76,
  dust = 77,
  aerosol_optical_depth = 78,
  carbon_monoxide = 79,
  nitrogen_dioxide = 80,
  ammonia = 81,
  ozone = 82,
  sulphur_dioxide = 83,
  alder_pollen = 84,
  birch_pollen = 85,
  grass_pollen = 86,
  mugwort_pollen = 87,
  olive_pollen = 88,
  ragweed_pollen = 89,
  european_aqi = 90,
  european_aqi_pm2p5 = 91,
  european_aqi_pm10 = 92,
  european_aqi_nitrogen_dioxide = 93,
  european_aqi_ozone = 94,
  european_aqi_sulphur_dioxide = 95,
  us_aqi = 96,
  us_aqi_pm2p5 = 97,
  us_aqi_pm10 = 98,
  us_aqi_nitrogen_dioxide = 99,
  us_aqi_ozone = 100,
  us_aqi_sulphur_dioxide = 101,
  us_aqi_carbon_monoxide = 102,
  sunshine_duration = 103,
  convective_inhibition = 104,
  shortwave_radiation_clear_sky = 105,
  global_tilted_irradiance = 106,
  global_tilted_irradiance_instant = 107,
  ocean_current_velocity = 108,
  ocean_current_direction = 109,
  cloud_base = 110,
  cloud_top = 111,
  mass_density = 112,
  boundary_layer_height = 113,
  formaldehyde = 114,
  glyoxal = 115,
  non_methane_volatile_organic_compounds = 116,
  pm10_wildfires = 117,
  peroxyacyl_nitrates = 118,
  secondary_inorganic_aerosol = 119,
  residential_elementary_carbon = 120,
  total_elementary_carbon = 121,
  pm2_5_total_organic_matter = 122,
  sea_salt_aerosol = 123,
  nitrogen_monoxide = 124,
  thunderstorm_probability = 125,
  rain_probability = 126,
  freezing_rain_probability = 127,
  ice_pellets_probability = 128,
  snowfall_probability = 129,
  carbon_dioxide = 130,
  methane = 131,
  sea_level_height_msl = 132,
  sea_surface_temperature = 133,
  invert_barometer_height = 134,
  hail = 135,
  albedo = 136,
  precipitation_type = 137,
  convective_cloud_base = 138,
  convective_cloud_top = 139,
  snow_depth_water_equivalent = 140,
  secondary_swell_wave_height = 141,
  secondary_swell_wave_period = 142,
  secondary_swell_wave_peak_period = 143,
  secondary_swell_wave_direction = 144,
  tertiary_swell_wave_height = 145,
  tertiary_swell_wave_period = 146,
  tertiary_swell_wave_peak_period = 147,
  tertiary_swell_wave_direction = 148,
  wind_u_component = 149,
  wind_v_component = 150,
  temperature_max24h = 151,
  temperature_min24h = 152,
  temperature_mean24h = 153,
  snow_density = 154,
  longwave_radiation = 155,
  sea_ice_cover = 156,
  k_index = 157,
  roughness_length = 158,
  potential_evapotranspiration = 159,
  wave_peak_period = 160,
  temperature_max6h = 161,
  temperature_min6h = 162,
  lightning_density = 163,
  sea_ice_thickness = 164,
  shortwave_radiation_clear_sky_instant = 165,
  sea_water_salinity = 166,
  total_column_water = 167,
  air_density = 168
};

inline const Variable (&EnumValuesVariable())[169] {
  static const Variable values[] = {
    Variable::undefined,
    Variable::apparent_temperature,
    Variable::cape,
    Variable::cloud_cover,
    Variable::cloud_cover_high,
    Variable::cloud_cover_low,
    Variable::cloud_cover_mid,
    Variable::daylight_duration,
    Variable::dew_point,
    Variable::diffuse_radiation,
    Variable::diffuse_radiation_instant,
    Variable::direct_normal_irradiance,
    Variable::direct_normal_irradiance_instant,
    Variable::direct_radiation,
    Variable::direct_radiation_instant,
    Variable::et0_fao_evapotranspiration,
    Variable::evapotranspiration,
    Variable::freezing_level_height,
    Variable::growing_degree_days,
    Variable::is_day,
    Variable::latent_heat_flux,
    Variable::leaf_wetness_probability,
    Variable::lifted_index,
    Variable::lightning_potential,
    Variable::precipitation,
    Variable::precipitation_hours,
    Variable::precipitation_probability,
    Variable::pressure_msl,
    Variable::rain,
    Variable::relative_humidity,
    Variable::runoff,
    Variable::sensible_heat_flux,
    Variable::shortwave_radiation,
    Variable::shortwave_radiation_instant,
    Variable::showers,
    Variable::snow_depth,
    Variable::snow_height,
    Variable::snowfall,
    Variable::snowfall_height,
    Variable::snowfall_water_equivalent,
    Variable::sunrise,
    Variable::sunset,
    Variable::soil_moisture,
    Variable::soil_moisture_index,
    Variable::soil_temperature,
    Variable::surface_pressure,
    Variable::surface_temperature,
    Variable::temperature,
    Variable::terrestrial_radiation,
    Variable::terrestrial_radiation_instant,
    Variable::total_column_integrated_water_vapour,
    Variable::updraft,
    Variable::uv_index,
    Variable::uv_index_clear_sky,
    Variable::vapour_pressure_deficit,
    Variable::visibility,
    Variable::weather_code,
    Variable::wind_direction,
    Variable::wind_gusts,
    Variable::wind_speed,
    Variable::vertical_velocity,
    Variable::geopotential_height,
    Variable::wet_bulb_temperature,
    Variable::river_discharge,
    Variable::wave_height,
    Variable::wave_period,
    Variable::wave_direction,
    Variable::wind_wave_height,
    Variable::wind_wave_period,
    Variable::wind_wave_peak_period,
    Variable::wind_wave_direction,
    Variable::swell_wave_height,
    Variable::swell_wave_period,
    Variable::swell_wave_peak_period,
    Variable::swell_wave_direction,
    Variable::pm10,
    Variable::pm2p5,
    Variable::dust,
    Variable::aerosol_optical_depth,
    Variable::carbon_monoxide,
    Variable::nitrogen_dioxide,
    Variable::ammonia,
    Variable::ozone,
    Variable::sulphur_dioxide,
    Variable::alder_pollen,
    Variable::birch_pollen,
    Variable::grass_pollen,
    Variable::mugwort_pollen,
    Variable::olive_pollen,
    Variable::ragweed_pollen,
    Variable::european_aqi,
    Variable::european_aqi_pm2p5,
    Variable::european_aqi_pm10,
    Variable::european_aqi_nitrogen_dioxide,
    Variable::european_aqi_ozone,
    Variable::european_aqi_sulphur_dioxide,
    Variable::us_aqi,
    Variable::us_aqi_pm2p5,
    Variable::us_aqi_pm10,
    Variable::us_aqi_nitrogen_dioxide,
    Variable::us_aqi_ozone,
    Variable::us_aqi_sulphur_dioxide,
    Variable::us_aqi_carbon_monoxide,
    Variable::sunshine_duration,
    Variable::convective_inhibition,
    Variable::shortwave_radiation_clear_sky,
    Variable::global_tilted_irradiance,
    Variable::global_tilted_irradiance_instant,
    Variable::ocean_current_velocity,
    Variable::ocean_current_direction,
    Variable::cloud_base,
    Variable::cloud_top,
    Variable::mass_density,
    Variable::boundary_layer_height,
    Variable::formaldehyde,
    Variable::glyoxal,
    Variable::non_methane_volatile_organic_compounds,
    Variable::pm10_wildfires,
    Variable::peroxyacyl_nitrates,
    Variable::secondary_inorganic_aerosol,
    Variable::residential_elementary_carbon,
    Variable::total_elementary_carbon,
    Variable::pm2_5_total_organic_matter,
    Variable::sea_salt_aerosol,
    Variable::nitrogen_monoxide,
    Variable::thunderstorm_probability,
    Variable::rain_probability,
    Variable::freezing_rain_probability,
    Variable::ice_pellets_probability,
    Variable::snowfall_probability,
    Variable::carbon_dioxide,
    Variable::methane,
    Variable::sea_level_height_msl,
    Variable::sea_surface_temperature,
    Variable::invert_barometer_height,
    Variable::hail,
    Variable::albedo,
    Variable::precipitation_type,
    Variable::convective_cloud_base,
    Variable::convective_cloud_top,
    Variable::snow_depth_water_equivalent,
    Variable::secondary_swell_wave_height,
    Variable::secondary_swell_wave_period,
    Variable::secondary_swell_wave_peak_period,
    Variable::secondary_swell_wave_direction,
    Variable::tertiary_swell_wave_height,
    Variable::tertiary_swell_wave_period,
    Variable::tertiary_swell_wave_peak_period,
    Variable::tertiary_swell_wave_direction,
    Variable::wind_u_component,
    Variable::wind_v_component,
    Variable::temperature_max24h,
    Variable::temperature_min24h,
    Variable::temperature_mean24h,
    Variable::snow_density,
    Variable::longwave_radiation,
    Variable::sea_ice_cover,
    Variable::k_index,
    Variable::roughness_length,
    Variable::potential_evapotranspiration,
    Variable::wave_peak_period,
    Variable::temperature_max6h,
    Variable::temperature_min6h,
    Variable::lightning_density,
    Variable::sea_ice_thickness,
    Variable::shortwave_radiation_clear_sky_instant,
    Variable::sea_water_salinity,
    Variable::total_column_water,
    Variable::air_density
  };
  return values;
}

inline const char * const *EnumNamesVariable() {
  static const char * const names[170] = {
    "undefined",
    "apparent_temperature",
    "cape",
    "cloud_cover",
    "cloud_cover_high",
    "cloud_cover_low",
    "cloud_cover_mid",
    "daylight_duration",
    "dew_point",
    "diffuse_radiation",
    "diffuse_radiation_instant",
    "direct_normal_irradiance",
    "direct_normal_irradiance_instant",
    "direct_radiation",
    "direct_radiation_instant",
    "et0_fao_evapotranspiration",
    "evapotranspiration",
    "freezing_level_height",
    "growing_degree_days",
    "is_day",
    "latent_heat_flux",
    "leaf_wetness_probability",
    "lifted_index",
    "lightning_potential",
    "precipitation",
    "precipitation_hours",
    "precipitation_probability",
    "pressure_msl",
    "rain",
    "relative_humidity",
    "runoff",
    "sensible_heat_flux",
    "shortwave_radiation",
    "shortwave_radiation_instant",
    "showers",
    "snow_depth",
    "snow_height",
    "snowfall",
    "snowfall_height",
    "snowfall_water_equivalent",
    "sunrise",
    "sunset",
    "soil_moisture",
    "soil_moisture_index",
    "soil_temperature",
    "surface_pressure",
    "surface_temperature",
    "temperature",
    "terrestrial_radiation",
    "terrestrial_radiation_instant",
    "total_column_integrated_water_vapour",
    "updraft",
    "uv_index",
    "uv_index_clear_sky",
    "vapour_pressure_deficit",
    "visibility",
    "weather_code",
    "wind_direction",
    "wind_gusts",
    "wind_speed",
    "vertical_velocity",
    "geopotential_height",
    "wet_bulb_temperature",
    "river_discharge",
    "wave_height",
    "wave_period",
    "wave_direction",
    "wind_wave_height",
    "wind_wave_period",
    "wind_wave_peak_period",
    "wind_wave_direction",
    "swell_wave_height",
    "swell_wave_period",
    "swell_wave_peak_period",
    "swell_wave_direction",
    "pm10",
    "pm2p5",
    "dust",
    "aerosol_optical_depth",
    "carbon_monoxide",
    "nitrogen_dioxide",
    "ammonia",
    "ozone",
    "sulphur_dioxide",
    "alder_pollen",
    "birch_pollen",
    "grass_pollen",
    "mugwort_pollen",
    "olive_pollen",
    "ragweed_pollen",
    "european_aqi",
    "european_aqi_pm2p5",
    "european_aqi_pm10",
    "european_aqi_nitrogen_dioxide",
    "european_aqi_ozone",
    "european_aqi_sulphur_dioxide",
    "us_aqi",
    "us_aqi_pm2p5",
    "us_aqi_pm10",
    "us_aqi_nitrogen_dioxide",
    "us_aqi_ozone",
    "us_aqi_sulphur_dioxide",
    "us_aqi_carbon_monoxide",
    "sunshine_duration",
    "convective_inhibition",
    "shortwave_radiation_clear_sky",
    "global_tilted_irradiance",
    "global_tilted_irradiance_instant",
    "ocean_current_velocity",
    "ocean_current_direction",
    "cloud_base",
    "cloud_top",
    "mass_density",
    "boundary_layer_height",
    "formaldehyde",
    "glyoxal",
    "non_methane_volatile_organic_compounds",
    "pm10_wildfires",
    "peroxyacyl_nitrates",
    "secondary_inorganic_aerosol",
    "residential_elementary_carbon",
    "total_elementary_carbon",
    "pm2_5_total_organic_matter",
    "sea_salt_aerosol",
    "nitrogen_monoxide",
    "thunderstorm_probability",
    "rain_probability",
    "freezing_rain_probability",
    "ice_pellets_probability",
    "snowfall_probability",
    "carbon_dioxide",
    "methane",
    "sea_level_height_msl",
    "sea_surface_temperature",
    "invert_barometer_height",
    "hail",
    "albedo",
    "precipitation_type",
    "convective_cloud_base",
    "convective_cloud_top",
    "snow_depth_water_equivalent",
    "secondary_swell_wave_height",
    "secondary_swell_wave_period",
    "secondary_swell_wave_peak_period",
    "secondary_swell_wave_direction",
    "tertiary_swell_wave_height",
    "tertiary_swell_wave_period",
    "tertiary_swell_wave_peak_period",
    "tertiary_swell_wave_direction",
    "wind_u_component",
    "wind_v_component",
    "temperature_max24h",
    "temperature_min24h",
    "temperature_mean24h",
    "snow_density",
    "longwave_radiation",
    "sea_ice_cover",
    "k_index",
    "roughness_length",
    "potential_evapotranspiration",
    "wave_peak_period",
    "temperature_max6h",
    "temperature_min6h",
    "lightning_density",
    "sea_ice_thickness",
    "shortwave_radiation_clear_sky_instant",
    "sea_water_salinity",
    "total_column_water",
    "air_density",
    nullptr
  };
  return names;
}

inline const char *EnumNameVariable(Variable e) {
  if (::flatbuffers::IsOutRange(e, Variable::undefined, Variable::air_density)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesVariable()[index];
}

enum class Aggregation : uint8_t {
  none = 0,
  minimum = 1,
  maximum = 2,
  mean = 3,
  p10 = 4,
  p25 = 5,
  median = 6,
  p75 = 7,
  p90 = 8,
  dominant = 9,
  sum = 10,
  spread = 11,
  anomaly = 12,
  sot10 = 13,
  sot90 = 14,
  efi = 15
};

inline const Aggregation (&EnumValuesAggregation())[16] {
  static const Aggregation values[] = {
    Aggregation::none,
    Aggregation::minimum,
    Aggregation::maximum,
    Aggregation::mean,
    Aggregation::p10,
    Aggregation::p25,
    Aggregation::median,
    Aggregation::p75,
    Aggregation::p90,
    Aggregation::dominant,
    Aggregation::sum,
    Aggregation::spread,
    Aggregation::anomaly,
    Aggregation::sot10,
    Aggregation::sot90,
    Aggregation::efi
  };
  return values;
}

inline const char * const *EnumNamesAggregation() {
  static const char * const names[17] = {
    "none",
    "minimum",
    "maximum",
    "mean",
    "p10",
    "p25",
    "median",
    "p75",
    "p90",
    "dominant",
    "sum",
    "spread",
    "anomaly",
    "sot10",
    "sot90",
    "efi",
    nullptr
  };
  return names;
}

inline const char *EnumNameAggregation(Aggregation e) {
  if (::flatbuffers::IsOutRange(e, Aggregation::none, Aggregation::efi)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAggregation()[index];
}

enum class Probability : uint8_t {
  none = 0,
  gt0 = 1,
  gt0p1 = 2,
  gt1 = 3,
  gt2 = 4,
  gt3 = 5,
  gt4 = 6,
  gt5 = 7,
  gt8 = 8,
  gt10 = 9,
  gt15 = 10,
  gt20 = 11,
  gt25 = 12,
  gt30 = 13,
  gt35 = 14,
  gt40 = 15,
  gt50 = 16,
  gt60 = 17,
  gt75 = 18,
  gt80 = 19,
  gt100 = 20,
  lt0 = 21,
  lt0p1 = 22,
  lt1 = 23,
  ltm1 = 24,
  ltm2 = 25,
  ltm3 = 26,
  ltm4 = 27,
  ltm5 = 28,
  ltm8 = 29,
  ltm10 = 30,
  ltm15 = 31,
  ltm20 = 32,
  gt1stdev = 33,
  gt1p5stdev = 34,
  gt2stdev = 35,
  lt1stdev = 36,
  lt1p5stdev = 37,
  lt2stdev = 38
};

inline const Probability (&EnumValuesProbability())[39] {
  static const Probability values[] = {
    Probability::none,
    Probability::gt0,
    Probability::gt0p1,
    Probability::gt1,
    Probability::gt2,
    Probability::gt3,
    Probability::gt4,
    Probability::gt5,
    Probability::gt8,
    Probability::gt10,
    Probability::gt15,
    Probability::gt20,
    Probability::gt25,
    Probability::gt30,
    Probability::gt35,
    Probability::gt40,
    Probability::gt50,
    Probability::gt60,
    Probability::gt75,
    Probability::gt80,
    Probability::gt100,
    Probability::lt0,
    Probability::lt0p1,
    Probability::lt1,
    Probability::ltm1,
    Probability::ltm2,
    Probability::ltm3,
    Probability::ltm4,
    Probability::ltm5,
    Probability::ltm8,
    Probability::ltm10,
    Probability::ltm15,
    Probability::ltm20,
    Probability::gt1stdev,
    Probability::gt1p5stdev,
    Probability::gt2stdev,
    Probability::lt1stdev,
    Probability::lt1p5stdev,
    Probability::lt2stdev
  };
  return values;
}

inline const char * const *EnumNamesProbability() {
  static const char * const names[40] = {
    "none",
    "gt0",
    "gt0p1",
    "gt1",
    "gt2",
    "gt3",
    "gt4",
    "gt5",
    "gt8",
    "gt10",
    "gt15",
    "gt20",
    "gt25",
    "gt30",
    "gt35",
    "gt40",
    "gt50",
    "gt60",
    "gt75",
    "gt80",
    "gt100",
    "lt0",
    "lt0p1",
    "lt1",
    "ltm1",
    "ltm2",
    "ltm3",
    "ltm4",
    "ltm5",
    "ltm8",
    "ltm10",
    "ltm15",
    "ltm20",
    "gt1stdev",
    "gt1p5stdev",
    "gt2stdev",
    "lt1stdev",
    "lt1p5stdev",
    "lt2stdev",
    nullptr
  };
  return names;
}

inline const char *EnumNameProbability(Probability e) {
  if (::flatbuffers::IsOutRange(e, Probability::none, Probability::lt2stdev)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesProbability()[index];
}

struct VariableWithValues FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VariableWithValuesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VARIABLE = 4,
    VT_UNIT = 6,
    VT_VALUE = 8,
    VT_VALUES = 10,
    VT_VALUES_INT64 = 12,
    VT_ALTITUDE = 14,
    VT_AGGREGATION = 16,
    VT_PRESSURE_LEVEL = 18,
    VT_DEPTH = 20,
    VT_DEPTH_TO = 22,
    VT_ENSEMBLE_MEMBER = 24,
    VT_PREVIOUS_DAY = 26,
    VT_PROBABILITY = 28
  };
  openmeteo_sdk::Variable variable() const {
    return static_cast<openmeteo_sdk::Variable>(GetField<uint8_t>(VT_VARIABLE, 0));
  }
  openmeteo_sdk::Unit unit() const {
    return static_cast<openmeteo_sdk::Unit>(GetField<uint8_t>(VT_UNIT, 0));
  }
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  const ::flatbuffers::Vector<float> *values() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_VALUES);
  }
  const ::flatbuffers::Vector<int64_t> *values_int64() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_VALUES_INT64);
  }
  int16_t altitude() const {
    return GetField<int16_t>(VT_ALTITUDE, 0);
  }
  openmeteo_sdk::Aggregation aggregation() const {
    return static_cast<openmeteo_sdk::Aggregation>(GetField<uint8_t>(VT_AGGREGATION, 0));
  }
  int16_t pressure_level() const {
    return GetField<int16_t>(VT_PRESSURE_LEVEL, 0);
  }
  int16_t depth() const {
    return GetField<int16_t>(VT_DEPTH, 0);
  }
  int16_t depth_to() const {
    return GetField<int16_t>(VT_DEPTH_TO, 0);
  }
  int16_t ensemble_member() const {
    return GetField<int16_t>(VT_ENSEMBLE_MEMBER, 0);
  }
  int16_t previous_day() const {
    return GetField<int16_t>(VT_PREVIOUS_DAY, 0);
  }
  openmeteo_sdk::Probability probability() const {
    return static_cast<openmeteo_sdk::Probability>(GetField<uint8_t>(VT_PROBABILITY, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VARIABLE, 1) &&
           VerifyField<uint8_t>(verifier, VT_UNIT, 1) &&
           VerifyField<float>(verifier, VT_VALUE, 4) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           VerifyOffset(verifier, VT_VALUES_INT64) &&
           verifier.VerifyVector(values_int64()) &&
           VerifyField<int16_t>(verifier, VT_ALTITUDE, 2) &&
           VerifyField<uint8_t>(verifier, VT_AGGREGATION, 1) &&
           VerifyField<int16_t>(verifier, VT_PRESSURE_LEVEL, 2) &&
           VerifyField<int16_t>(verifier, VT_DEPTH, 2) &&
           VerifyField<int16_t>(verifier, VT_DEPTH_TO, 2) &&
           VerifyField<int16_t>(verifier, VT_ENSEMBLE_MEMBER, 2) &&
           VerifyField<int16_t>(verifier, VT_PREVIOUS_DAY, 2) &&
           VerifyField<uint8_t>(verifier, VT_PROBABILITY, 1) &&
           verifier.EndTable();
  }
};

struct VariableWithValuesBuilder {
  typedef VariableWithValues Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_variable(openmeteo_sdk::Variable variable) {
    fbb_.AddElement<uint8_t>(VariableWithValues::VT_VARIABLE, static_cast<uint8_t>(variable), 0);
  }
  void add_unit(openmeteo_sdk::Unit unit) {
    fbb_.AddElement<uint8_t>(VariableWithValues::VT_UNIT, static_cast<uint8_t>(unit), 0);
  }
  void add_value(float value) {
    fbb_.AddElement<float>(VariableWithValues::VT_VALUE, value, 0.0f);
  }
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<float>> values) {
    fbb_.AddOffset(VariableWithValues::VT_VALUES, values);
  }
  void add_values_int64(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> values_int64) {
    fbb_.AddOffset(VariableWithValues::VT_VALUES_INT64, values_int64);
  }
  void add_altitude(int16_t altitude) {
    fbb_.AddElement<int16_t>(VariableWithValues::VT_ALTITUDE, altitude, 0);
  }
  void add_aggregation(openmeteo_sdk::Aggregation aggregation) {
    fbb_.AddElement<uint8_t>(VariableWithValues::VT_AGGREGATION, static_cast<uint8_t>(aggregation), 0);
  }
  void add_pressure_level(int16_t pressure_level) {
    fbb_.AddElement<int16_t>(VariableWithValues::VT_PRESSURE_LEVEL, pressure_level, 0);
  }
  void add_depth(int16_t depth) {
    fbb_.AddElement<int16_t>(VariableWithValues::VT_DEPTH, depth, 0);
  }
  void add_depth_to(int16_t depth_to) {
    fbb_.AddElement<int16_t>(VariableWithValues::VT_DEPTH_TO, depth_to, 0);
  }
  void add_ensemble_member(int16_t ensemble_member) {
    fbb_.AddElement<int16_t>(VariableWithValues::VT_ENSEMBLE_MEMBER, ensemble_member, 0);
  }
  void add_previous_day(int16_t previous_day) {
    fbb_.AddElement<int16_t>(VariableWithValues::VT_PREVIOUS_DAY, previous_day, 0);
  }
  void add_probability(openmeteo_sdk::Probability probability) {
    fbb_.AddElement<uint8_t>(VariableWithValues::VT_PROBABILITY, static_cast<uint8_t>(probability), 0);
  }
  explicit VariableWithValuesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VariableWithValues> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VariableWithValues>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VariableWithValues> CreateVariableWithValues(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    openmeteo_sdk::Variable variable = openmeteo_sdk::Variable::undefined,
    openmeteo_sdk::Unit unit = openmeteo_sdk::Unit::undefined,
    float value = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> values = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> values_int64 = 0,
    int16_t altitude = 0,
    openmeteo_sdk::Aggregation aggregation = openmeteo_sdk::Aggregation::none,
    int16_t pressure_level = 0,
    int16_t depth = 0,
    int16_t depth_to = 0,
    int16_t ensemble_member = 0,
    int16_t previous_day = 0,
    openmeteo_sdk::Probability probability = openmeteo_sdk::Probability::none) {
  VariableWithValuesBuilder builder_(_fbb);
  builder_.add_values_int64(values_int64);
  builder_.add_values(values);
  builder_.add_value(value);
  builder_.add_previous_day(previous_day);
  builder_.add_ensemble_member(ensemble_member);
  builder_.add_depth_to(depth_to);
  builder_.add_depth(depth);
  builder_.add_pressure_level(pressure_level);
  builder_.add_altitude(altitude);
  builder_.add_probability(probability);
  builder_.add_aggregation(aggregation);
  builder_.add_unit(unit);
  builder_.add_variable(variable);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VariableWithValues> CreateVariableWithValuesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    openmeteo_sdk::Variable variable = openmeteo_sdk::Variable::undefined,
    openmeteo_sdk::Unit unit = openmeteo_sdk::Unit::undefined,
    float value = 0.0f,
    const std::vector<float> *values = nullptr,
    const std::vector<int64_t> *values_int64 = nullptr,
    int16_t altitude = 0,
    openmeteo_sdk::Aggregation aggregation = openmeteo_sdk::Aggregation::none,
    int16_t pressure_level = 0,
    int16_t depth = 0,
    int16_t depth_to = 0,
    int16_t ensemble_member = 0,
    int16_t previous_day = 0,
    openmeteo_sdk::Probability probability = openmeteo_sdk::Probability::none) {
  auto values__ = values ? _fbb.CreateVector<float>(*values) : 0;
  auto values_int64__ = values_int64 ? _fbb.CreateVector<int64_t>(*values_int64) : 0;
  return openmeteo_sdk::CreateVariableWithValues(
      _fbb,
      variable,
      unit,
      value,
      values__,
      values_int64__,
      altitude,
      aggregation,
      pressure_level,
      depth,
      depth_to,
      ensemble_member,
      previous_day,
      probability);
}

struct VariablesWithTime FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VariablesWithTimeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIME = 4,
    VT_TIME_END = 6,
    VT_INTERVAL = 8,
    VT_VARIABLES = 10
  };
  int64_t time() const {
    return GetField<int64_t>(VT_TIME, 0);
  }
  int64_t time_end() const {
    return GetField<int64_t>(VT_TIME_END, 0);
  }
  int32_t interval() const {
    return GetField<int32_t>(VT_INTERVAL, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<openmeteo_sdk::VariableWithValues>> *variables() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<openmeteo_sdk::VariableWithValues>> *>(VT_VARIABLES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_TIME, 8) &&
           VerifyField<int64_t>(verifier, VT_TIME_END, 8) &&
           VerifyField<int32_t>(verifier, VT_INTERVAL, 4) &&
           VerifyOffset(verifier, VT_VARIABLES) &&
           verifier.VerifyVector(variables()) &&
           verifier.VerifyVectorOfTables(variables()) &&
           verifier.EndTable();
  }
};

struct VariablesWithTimeBuilder {
  typedef VariablesWithTime Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_time(int64_t time) {
    fbb_.AddElement<int64_t>(VariablesWithTime::VT_TIME, time, 0);
  }
  void add_time_end(int64_t time_end) {
    fbb_.AddElement<int64_t>(VariablesWithTime::VT_TIME_END, time_end, 0);
  }
  void add_interval(int32_t interval) {
    fbb_.AddElement<int32_t>(VariablesWithTime::VT_INTERVAL, interval, 0);
  }
  void add_variables(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<openmeteo_sdk::VariableWithValues>>> variables) {
    fbb_.AddOffset(VariablesWithTime::VT_VARIABLES, variables);
  }
  explicit VariablesWithTimeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VariablesWithTime> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VariablesWithTime>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VariablesWithTime> CreateVariablesWithTime(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t time = 0,
    int64_t time_end = 0,
    int32_t interval = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<openmeteo_sdk::VariableWithValues>>> variables = 0) {
  VariablesWithTimeBuilder builder_(_fbb);
  builder_.add_time_end(time_end);
  builder_.add_time(time);
  builder_.add_variables(variables);
  builder_.add_interval(interval);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VariablesWithTime> CreateVariablesWithTimeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t time = 0,
    int64_t time_end = 0,
    int32_t interval = 0,
    const std::vector<::flatbuffers::Offset<openmeteo_sdk::VariableWithValues>> *variables = nullptr) {
  auto variables__ = variables ? _fbb.CreateVector<::flatbuffers::Offset<openmeteo_sdk::VariableWithValues>>(*variables) : 0;
  return openmeteo_sdk::CreateVariablesWithTime(
      _fbb,
      time,
      time_end,
      interval,
      variables__);
}

struct VariablesWithMonth FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VariablesWithMonthBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_YEAR = 4,
    VT_MONTH = 6,
    VT_COUNT = 8,
    VT_VARIABLES = 10
  };
  int16_t year() const {
    return GetField<int16_t>(VT_YEAR, 0);
  }
  int8_t month() const {
    return GetField<int8_t>(VT_MONTH, 0);
  }
  int32_t count() const {
    return GetField<int32_t>(VT_COUNT, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<openmeteo_sdk::VariableWithValues>> *variables() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<openmeteo_sdk::VariableWithValues>> *>(VT_VARIABLES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_YEAR, 2) &&
           VerifyField<int8_t>(verifier, VT_MONTH, 1) &&
           VerifyField<int32_t>(verifier, VT_COUNT, 4) &&
           VerifyOffset(verifier, VT_VARIABLES) &&
           verifier.VerifyVector(variables()) &&
           verifier.VerifyVectorOfTables(variables()) &&
           verifier.EndTable();
  }
};

struct VariablesWithMonthBuilder {
  typedef VariablesWithMonth Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_year(int16_t year) {
    fbb_.AddElement<int16_t>(VariablesWithMonth::VT_YEAR, year, 0);
  }
  void add_month(int8_t month) {
    fbb_.AddElement<int8_t>(VariablesWithMonth::VT_MONTH, month, 0);
  }
  void add_count(int32_t count) {
    fbb_.AddElement<int32_t>(VariablesWithMonth::VT_COUNT, count, 0);
  }
  void add_variables(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<openmeteo_sdk::VariableWithValues>>> variables) {
    fbb_.AddOffset(VariablesWithMonth::VT_VARIABLES, variables);
  }
  explicit VariablesWithMonthBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VariablesWithMonth> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VariablesWithMonth>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VariablesWithMonth> CreateVariablesWithMonth(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t year = 0,
    int8_t month = 0,
    int32_t count = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<openmeteo_sdk::VariableWithValues>>> variables = 0) {
  VariablesWithMonthBuilder builder_(_fbb);
  builder_.add_variables(variables);
  builder_.add_count(count);
  builder_.add_year(year);
  builder_.add_month(month);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VariablesWithMonth> CreateVariablesWithMonthDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t year = 0,
    int8_t month = 0,
    int32_t count = 0,
    const std::vector<::flatbuffers::Offset<openmeteo_sdk::VariableWithValues>> *variables = nullptr) {
  auto variables__ = variables ? _fbb.CreateVector<::flatbuffers::Offset<openmeteo_sdk::VariableWithValues>>(*variables) : 0;
  return openmeteo_sdk::CreateVariablesWithMonth(
      _fbb,
      year,
      month,
      count,
      variables__);
}

struct WeatherApiResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WeatherApiResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LATITUDE = 4,
    VT_LONGITUDE = 6,
    VT_ELEVATION = 8,
    VT_GENERATION_TIME_MILLISECONDS = 10,
    VT_LOCATION_ID = 12,
    VT_MODEL = 14,
    VT_UTC_OFFSET_SECONDS = 16,
    VT_TIMEZONE = 18,
    VT_TIMEZONE_ABBREVIATION = 20,
    VT_CURRENT = 22,
    VT_DAILY = 24,
    VT_HOURLY = 26,
    VT_MINUTELY_15 = 28,
    VT_MONTHLY = 30,
    VT_WEEKLY = 32
  };
  float latitude() const {
    return GetField<float>(VT_LATITUDE, 0.0f);
  }
  float longitude() const {
    return GetField<float>(VT_LONGITUDE, 0.0f);
  }
  float elevation() const {
    return GetField<float>(VT_ELEVATION, 0.0f);
  }
  float generation_time_milliseconds() const {
    return GetField<float>(VT_GENERATION_TIME_MILLISECONDS, 0.0f);
  }
  int64_t location_id() const {
    return GetField<int64_t>(VT_LOCATION_ID, 0);
  }
  openmeteo_sdk::Model model() const {
    return static_cast<openmeteo_sdk::Model>(GetField<uint8_t>(VT_MODEL, 0));
  }
  int32_t utc_offset_seconds() const {
    return GetField<int32_t>(VT_UTC_OFFSET_SECONDS, 0);
  }
  const ::flatbuffers::String *timezone() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TIMEZONE);
  }
  const ::flatbuffers::String *timezone_abbreviation() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TIMEZONE_ABBREVIATION);
  }
  const openmeteo_sdk::VariablesWithTime *current() const {
    return GetPointer<const openmeteo_sdk::VariablesWithTime *>(VT_CURRENT);
  }
  const openmeteo_sdk::VariablesWithTime *daily() const {
    return GetPointer<const openmeteo_sdk::VariablesWithTime *>(VT_DAILY);
  }
  const openmeteo_sdk::VariablesWithTime *hourly() const {
    return GetPointer<const openmeteo_sdk::VariablesWithTime *>(VT_HOURLY);
  }
  const openmeteo_sdk::VariablesWithTime *minutely_15() const {
    return GetPointer<const openmeteo_sdk::VariablesWithTime *>(VT_MINUTELY_15);
  }
  const openmeteo_sdk::VariablesWithMonth *monthly() const {
    return GetPointer<const openmeteo_sdk::VariablesWithMonth *>(VT_MONTHLY);
  }
  const openmeteo_sdk::VariablesWithTime *weekly() const {
    return GetPointer<const openmeteo_sdk::VariablesWithTime *>(VT_WEEKLY);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_LATITUDE, 4) &&
           VerifyField<float>(verifier, VT_LONGITUDE, 4) &&
           VerifyField<float>(verifier, VT_ELEVATION, 4) &&
           VerifyField<float>(verifier, VT_GENERATION_TIME_MILLISECONDS, 4) &&
           VerifyField<int64_t>(verifier, VT_LOCATION_ID, 8) &&
           VerifyField<uint8_t>(verifier, VT_MODEL, 1) &&
           VerifyField<int32_t>(verifier, VT_UTC_OFFSET_SECONDS, 4) &&
           VerifyOffset(verifier, VT_TIMEZONE) &&
           verifier.VerifyString(timezone()) &&
           VerifyOffset(verifier, VT_TIMEZONE_ABBREVIATION) &&
           verifier.VerifyString(timezone_abbreviation()) &&
           VerifyOffset(verifier, VT_CURRENT) &&
           verifier.VerifyTable(current()) &&
           VerifyOffset(verifier, VT_DAILY) &&
           verifier.VerifyTable(daily()) &&
           VerifyOffset(verifier, VT_HOURLY) &&
           verifier.VerifyTable(hourly()) &&
           VerifyOffset(verifier, VT_MINUTELY_15) &&
           verifier.VerifyTable(minutely_15()) &&
           VerifyOffset(verifier, VT_MONTHLY) &&
           verifier.VerifyTable(monthly()) &&
           VerifyOffset(verifier, VT_WEEKLY) &&
           verifier.VerifyTable(weekly()) &&
           verifier.EndTable();
  }
};

struct WeatherApiResponseBuilder {
  typedef WeatherApiResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_latitude(float latitude) {
    fbb_.AddElement<float>(WeatherApiResponse::VT_LATITUDE, latitude, 0.0f);
  }
  void add_longitude(float longitude) {
    fbb_.AddElement<float>(WeatherApiResponse::VT_LONGITUDE, longitude, 0.0f);
  }
  void add_elevation(float elevation) {
    fbb_.AddElement<float>(WeatherApiResponse::VT_ELEVATION, elevation, 0.0f);
  }
  void add_generation_time_milliseconds(float generation_time_milliseconds) {
    fbb_.AddElement<float>(WeatherApiResponse::VT_GENERATION_TIME_MILLISECONDS, generation_time_milliseconds, 0.0f);
  }
  void add_location_id(int64_t location_id) {
    fbb_.AddElement<int64_t>(WeatherApiResponse::VT_LOCATION_ID, location_id, 0);
  }
  void add_model(openmeteo_sdk::Model model) {
    fbb_.AddElement<uint8_t>(WeatherApiResponse::VT_MODEL, static_cast<uint8_t>(model), 0);
  }
  void add_utc_offset_seconds(int32_t utc_offset_seconds) {
    fbb_.AddElement<int32_t>(WeatherApiResponse::VT_UTC_OFFSET_SECONDS, utc_offset_seconds, 0);
  }
  void add_timezone(::flatbuffers::Offset<::flatbuffers::String> timezone) {
    fbb_.AddOffset(WeatherApiResponse::VT_TIMEZONE, timezone);
  }
  void add_timezone_abbreviation(::flatbuffers::Offset<::flatbuffers::String> timezone_abbreviation) {
    fbb_.AddOffset(WeatherApiResponse::VT_TIMEZONE_ABBREVIATION, timezone_abbreviation);
  }
  void add_current(::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> current) {
    fbb_.AddOffset(WeatherApiResponse::VT_CURRENT, current);
  }
  void add_daily(::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> daily) {
    fbb_.AddOffset(WeatherApiResponse::VT_DAILY, daily);
  }
  void add_hourly(::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> hourly) {
    fbb_.AddOffset(WeatherApiResponse::VT_HOURLY, hourly);
  }
  void add_minutely_15(::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> minutely_15) {
    fbb_.AddOffset(WeatherApiResponse::VT_MINUTELY_15, minutely_15);
  }
  void add_monthly(::flatbuffers::Offset<openmeteo_sdk::VariablesWithMonth> monthly) {
    fbb_.AddOffset(WeatherApiResponse::VT_MONTHLY, monthly);
  }
  void add_weekly(::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> weekly) {
    fbb_.AddOffset(WeatherApiResponse::VT_WEEKLY, weekly);
  }
  explicit WeatherApiResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WeatherApiResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WeatherApiResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WeatherApiResponse> CreateWeatherApiResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float latitude = 0.0f,
    float longitude = 0.0f,
    float elevation = 0.0f,
    float generation_time_milliseconds = 0.0f,
    int64_t location_id = 0,
    openmeteo_sdk::Model model = openmeteo_sdk::Model::undefined,
    int32_t utc_offset_seconds = 0,
    ::flatbuffers::Offset<::flatbuffers::String> timezone = 0,
    ::flatbuffers::Offset<::flatbuffers::String> timezone_abbreviation = 0,
    ::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> current = 0,
    ::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> daily = 0,
    ::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> hourly = 0,
    ::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> minutely_15 = 0,
    ::flatbuffers::Offset<openmeteo_sdk::VariablesWithMonth> monthly = 0,
    ::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> weekly = 0) {
  WeatherApiResponseBuilder builder_(_fbb);
  builder_.add_location_id(location_id);
  builder_.add_weekly(weekly);
  builder_.add_monthly(monthly);
  builder_.add_minutely_15(minutely_15);
  builder_.add_hourly(hourly);
  builder_.add_daily(daily);
  builder_.add_current(current);
  builder_.add_timezone_abbreviation(timezone_abbreviation);
  builder_.add_timezone(timezone);
  builder_.add_utc_offset_seconds(utc_offset_seconds);
  builder_.add_generation_time_milliseconds(generation_time_milliseconds);
  builder_.add_elevation(elevation);
  builder_.add_longitude(longitude);
  builder_.add_latitude(latitude);
  builder_.add_model(model);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<WeatherApiResponse> CreateWeatherApiResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float latitude = 0.0f,
    float longitude = 0.0f,
    float elevation = 0.0f,
    float generation_time_milliseconds = 0.0f,
    int64_t location_id = 0,
    openmeteo_sdk::Model model = openmeteo_sdk::Model::undefined,
    int32_t utc_offset_seconds = 0,
    const char *timezone = nullptr,
    const char *timezone_abbreviation = nullptr,
    ::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> current = 0,
    ::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> daily = 0,
    ::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> hourly = 0,
    ::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> minutely_15 = 0,
    ::flatbuffers::Offset<openmeteo_sdk::VariablesWithMonth> monthly = 0,
    ::flatbuffers::Offset<openmeteo_sdk::VariablesWithTime> weekly = 0) {
  auto timezone__ = timezone ? _fbb.CreateString(timezone) : 0;
  auto timezone_abbreviation__ = timezone_abbreviation ? _fbb.CreateString(timezone_abbreviation) : 0;
  return openmeteo_sdk::CreateWeatherApiResponse(
      _fbb,
      latitude,
      longitude,
      elevation,
      generation_time_milliseconds,
      location_id,
      model,
      utc_offset_seconds,
      timezone__,
      timezone_abbreviation__,
      current,
      daily,
      hourly,
      minutely_15,
      monthly,
      weekly);
}

inline const openmeteo_sdk::WeatherApiResponse *GetWeatherApiResponse(const void *buf) {
  return ::flatbuffers::GetRoot<openmeteo_sdk::WeatherApiResponse>(buf);
}

inline const openmeteo_sdk::WeatherApiResponse *GetSizePrefixedWeatherApiResponse(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<openmeteo_sdk::WeatherApiResponse>(buf);
}

template <bool B = false>
inline bool VerifyWeatherApiResponseBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<openmeteo_sdk::WeatherApiResponse>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedWeatherApiResponseBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<openmeteo_sdk::WeatherApiResponse>(nullptr);
}

inline void FinishWeatherApiResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<openmeteo_sdk::WeatherApiResponse> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedWeatherApiResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<openmeteo_sdk::WeatherApiResponse> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace openmeteo_sdk

#endif  // FLATBUFFERS_GENERATED_WEATHERAPI_OPENMETEO_SDK_H_
